### ISSUE TITLE
TypeError: Cannot read property 'search' of undefined

### ISSUE THREAD

**Issue by az-ericso** [auth0/node-xml-encryption#15]
I am getting this error when using saml2.js and passport-saml.  The problem is due to the node-forge not update to date.

``` sh
/Users/kklh716/az/kancho/web/rubix-3.0/node_modules/saml2-js/node_modules/xml-encryption/node_modules/node-forge/js/util.js:1320
          _queryVariables = parse(window.location.search.substring(1));
                                                 ^

TypeError: Cannot read property 'search' of undefined
    at Object.util.getQueryVariables (/Users/kklh716/az/kancho/web/rubix-3.0/node_modules/saml2-js/node_modules/xml-encryption/node_modules/node-forge/js/util.js:1320:50)
    at Array.initModule (/Users/kklh716/az/kancho/web/rubix-3.0/node_modules/saml2-js/node_modules/xml-encryption/node_modules/node-forge/js/log.js:306:26)
    at Array.module.exports (/Users/kklh716/az/kancho/web/rubix-3.0/node_modules/saml2-js/node_modules/xml-encryption/node_modules/node-forge/js/log.js:359:14)
    at Module.module.exports (/Users/kklh716/az/kancho/web/rubix-3.0/node_modules/saml2-js/node_modules/xml-encryption/node_modules/node-forge/js/forge.js:42:14)
    at defineFunc (/Users/kklh716/az/kancho/web/rubix-3.0/node_modules/saml2-js/node_modules/xml-encryption/node_modules/node-forge/js/forge.js:48:10)
    at /Users/kklh716/az/kancho/web/rubix-3.0/node_modules/saml2-js/node_modules/xml-encryption/node_modules/node-forge/js/forge.js:86:14
    at define (/Users/kklh716/az/kancho/web/rubix-3.0/node_modules/saml2-js/node_modules/xml-encryption/node_modules/node-forge/js/forge.js:15:7)
    at define (/Users/kklh716/az/kancho/web/rubix-3.0/node_modules/saml2-js/node_modules/xml-encryption/node_modules/node-forge/js/forge.js:55:22)
    at /Users/kklh716/az/kancho/web/rubix-3.0/node_modules/saml2-js/node_modules/xml-encryption/node_modules/node-forge/js/forge.js:60:1
    at Object.<anonymous> (/Users/kklh716/az/kancho/web/rubix-3.0/node_modules/saml2-js/node_modules/xml-encryption/node_modules/node-forge/js/forge.js:88:3)
```

**Comment by gkwang** [comment]
Hi! 
we currently do not have node-forge pinned so there should not be an out-of-date problem. 
Since this is a 3 year old issue, I'm closing it for now, but if you're still seeing problem feel free to re-open.
