### ISSUE TITLE
`decrypt` throws when using  single line private key after update to `2.0.0`

### ISSUE THREAD

**Issue by christian-hawk** [auth0/node-xml-encryption#99]
### Description

After upgrading to version 2.0.0, `decrypt` throws when using single line private key. (without pvk header/footer and without line breaks). As reported in https://github.com/node-saml/passport-saml/issues/672 and https://github.com/GluuFederation/inbound-saml/issues/154 . 

This is happening because 'node-forge' used to accept a "single line" certificate in `private_key = pki.privateKeyFromPem(options.key)` (check commit https://github.com/auth0/node-xml-encryption/commit/7aaa7340b1428db4d00737777c4866440aa84c8f). But now, after this commit,  `crypto` module is in use:
https://github.com/auth0/node-xml-encryption/blob/e8df80cce4b0f1442fb14f526dc94b7a5bd0fe34/lib/xmlenc.js#L258

> Provide a clear and concise description of the issue, including what you expected to happen.

### Reproduction
```javascript
const rsaKey = fs.readFileSync(__dirname + '/your_private_key.key')
	.replace(/(\r\n|\n|\r)/gm, '')
    .replace('-----BEGIN RSA PRIVATE KEY-----', '')
    .replace('-----END RSA PRIVATE KEY-----', '')

const options = {
    key: rsaKey
}

xmlenc.decrypt('<xenc:EncryptedData ..... </xenc:EncryptedData>', options, function(err, result) {
	if(err) { 
		throw new Error(err)
	}
    console.log(result);
}
```

output:
```
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.privateDecrypt (node:internal/crypto/cipher:79:12)
    at decryptKeyInfoWithScheme (/root/inbound-saml-0.17.0/node_modules/xml-encryption/lib/xmlenc.js:258:26)
    at decryptKeyInfo (/root/inbound-saml-0.17.0/node_modules/xml-encryption/lib/xmlenc.js:246:14)
    at Object.decrypt (/root/inbound-saml-0.17.0/node_modules/xml-encryption/lib/xmlenc.js:187:24)
```

### Environment

> Please provide the following:

- **Version of this library used:** 2.0.0

### Adicional Context

Even if that depends on a lib (node-forge/crypto), this change caused downstream modules to **BREAK**, so from a design perspective it's still an **UNDOCUMENTED BREAKING CHANGE**, even that it may also be treated as a bug to (hot)fix.

**Comment by christian-hawk** [comment]
is this repo active?
